FROM python:3.12

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY ./requirements-dev.txt /app/requirements-dev.txt
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

COPY ./ /app

# CMD [ "python"]
CMD [ "jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser","--NotebookApp.token=''","--NotebookApp.password=''"]